M48
; DRILL file {KiCad 8.0.2-1} date 2025-01-26T22:20:56-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-26T22:20:56-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,Plated,3,4,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.200
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.300
%
G90
G05
T1
X50.0Y-46.0
T2
X47.46Y-54.0
M30
